var BATTLE = BATTLE || {};

BATTLE.MAX_DELAY = 12
BATTLE.FRAME_PERIOD = 9
BATTLE.PERIOD_TO_FIX_DELAY = 30

BATTLE.ROWS = 5
BATTLE.COLUMNS = 7

BATTLE.NUMBER_OF_TREE = 2
BATTLE.NUMBER_OF_HOLE = 1

BATTLE.TMP_TYPE = -2
BATTLE.LAND_TYPE = -1
BATTLE.HOLE_TYPE = 0
BATTLE.TREE_TYPE = 1
BATTLE.TOWER_TYPE = 2

BATTLE.EFFECT_DECREASE_HP = true

BATTLE.STARTING_POINT = cc.p(0,0)
BATTLE.TARGET_POINT = cc.p(BATTLE.ROWS-1, BATTLE.COLUMNS)

BATTLE.TOP_NEIGHBOR = cc.p(-1,0)
BATTLE.RIGHT_NEIGHBOR = cc.p(0,1)
BATTLE.BOTTOM_NEIGHBOR = cc.p(1,0)
BATTLE.LEFT_NEIGHBOR = cc.p(0,-1)

BATTLE.BOTTOM_NEIGHBOR_INDEX = 0
BATTLE.RIGHT_NEIGHBOR_INDEX = 1
BATTLE.TOP_NEIGHBOR_INDEX = 2
BATTLE.LEFT_NEIGHBOR_INDEX = 3

BATTLE.LIST_4_DIRECTION = [BATTLE.BOTTOM_NEIGHBOR,BATTLE.RIGHT_NEIGHBOR, BATTLE.TOP_NEIGHBOR, BATTLE.LEFT_NEIGHBOR]
BATTLE.LIST_8_DIRECTION = [
    cc.p(-1,-1),cc.p(-1,0), cc.p(-1,1),cc.p(0,1),
    cc.p(1,1), cc.p(1,0), cc.p(1,-1),cc.p(0,-1)
]

BATTLE.LIST_PRIORITY_DIRECTION_FOR_CURRENT_DIRECTION = [
    [BATTLE.BOTTOM_NEIGHBOR,BATTLE.TOP_NEIGHBOR,BATTLE.LEFT_NEIGHBOR],
    [BATTLE.RIGHT_NEIGHBOR,BATTLE.TOP_NEIGHBOR, BATTLE.LEFT_NEIGHBOR],
    [BATTLE.BOTTOM_NEIGHBOR,BATTLE.RIGHT_NEIGHBOR,BATTLE.TOP_NEIGHBOR],
    [BATTLE.RIGHT_NEIGHBOR,BATTLE.BOTTOM_NEIGHBOR,BATTLE.LEFT_NEIGHBOR]
]
BATTLE.PRIORITY_DIRECTION_LIST_INDEX_LEFT = 0
BATTLE.PRIORITY_DIRECTION_LIST_INDEX_UP = 1
BATTLE.PRIORITY_DIRECTION_LIST_INDEX_RIGHT = 2
BATTLE.PRIORITY_DIRECTION_LIST_INDEX_DOWN = 3

//--------------- 8 direction ---------------------
BATTLE.TOP_LEFT =0
BATTLE.TOP = 1
BATTLE.TOP_RIGHT = 2
BATTLE.LEFT = 3
BATTLE.RIGHT = 5
BATTLE.BOTTOM_LEFT = 6
BATTLE.BOTTOM = 7
BATTLE.BOTTOM_RIGHT = 8
BATTLE.MAP_DIRECTION_TOP_LEFT_ORIGIN = [
    [BATTLE.TOP_LEFT, BATTLE.TOP, BATTLE.TOP_RIGHT],
    [BATTLE.LEFT,,BATTLE.RIGHT],
    [BATTLE.BOTTOM_LEFT, BATTLE.BOTTOM, BATTLE.BOTTOM_RIGHT]
]
//--------------------------------------------------
// HashDirection = "flagDown + flagUp + flagRight + flagLeft"
// direction: 0 - di xuong, 1 - di cheo xuong, 2 - di ngang, 3 - di cheo len, 4 - di len
BATTLE.HASH_DIRECTION = {
    "1010": {"direction": 1, "flipX": false},
    "0110": {"direction": 3, "flipX": false},
    "0101": {"direction": 3, "flipX": true},
    "1001": {"direction": 1, "flipX": true},
    "0001": {"direction": 2, "flipX": true},
    "0010": {"direction": 2, "flipX": false},
    "1000": {"direction": 0, "flipX": false},
    "0100": {"direction": 4, "flipX": false},
}
//--------------------------------------------------
BATTLE.MONSTER_DIRECTION_TOP = 0
BATTLE.MONSTER_DIRECTION_RIGHT = 1
BATTLE.MONSTER_DIRECTION_BOTTOM = 2
BATTLE.MONSTER_DIRECTION_LEFT = 3
//--------------------------------------------------

BATTLE.NO_BUFF = -1
BATTLE.LIST_BUFF = [
    {"name": "attack_speed"},
    {"name": "damage"},
    {"name": "range"}
]
BATTLE.RANGE_BUFF_ROWS = 3
BATTLE.RANGE_BUFF_CLOUMNS = 5

BATTLE.CONTROL_PANEL_HEIGHT = 0
BATTLE.INIT_ENERGY = 15
BATTLE.SQUARE_SIZE = SCREEN.RESOLUTION.HEIGHT * 0.83 / 14;
BATTLE.FLAG_TRACE_CHECKED = -2
BATTLE.FLAG_TRACE_INIT = -1
BATTLE.SPACE_EACH_SIDE = 1
BATTLE.MAX_SPEED = 50
BATTLE.TIME_DELAY_MAX = 5
BATTLE.SUFFIX_PNG = ".png"
BATTLE.SUFFIX_JSON = ".json"
BATTLE.SUFFIX_ATLAS = ".atlas"
BATTLE.BIG_NUMBER = 9999
BATTLE.WHITE_COLOR = "FFFFFF"
BATTLE.BLUE_COLOR = "78d0e4"
BATTLE.MAX_COUNT_RANDOM = 200
BATTLE.DELTA_DISTANCE = 0.001
BATTLE.COST_TURN_DIJKSTRA = 1
BATTLE.COST_STRAIGHT_DIJKSTRA = BATTLE.ROWS*BATTLE.COLUMNS*2
BATTLE.FLAG_SHOW_PATH = "showPath"
BATTLE.FLAG_SUGGESTION_PATH = "suggestionPath"
BATTLE.SCORE_TURN = 1
BATTLE.SCORE_STRAIGHT = BATTLE.ROWS*BATTLE.COLUMNS
BATTLE.SCORE_BUFF_NEIGHBOR = BATTLE.ROWS*BATTLE.COLUMNS*BATTLE.ROWS*BATTLE.COLUMNS
BATTLE.INIT_WEIGHT = 50

BATTLE.RIVER_HEIGHT = 1
BATTLE.REVERT_COLOR = {r:255, g:255, b:255}
BATTLE.EFFECT_COLOR = {r:192, g:192, b:192}

BATTLE.RESULT_DRAW_TXT = "draw"
BATTLE.RESULT_LOSE_TXT = "lose"
BATTLE.RESULT_WIN_TXT = "win"

BATTLE.RESULT_DRAW = -1
BATTLE.RESULT_LOSE = 0
BATTLE.RESULT_WIN = 1

BATTLE.MAX_TURN = 20

BATTLE.INIT_HP = 20
BATTLE.INIT_ENERGY = 15
BATTLE.MAX_ENERGY = 30

// BATTLE.INIT_HP = 1
// BATTLE.INIT_ENERGY = 1000
// BATTLE.MAX_ENERGY = 1000

BATTLE.INIT_TIME_COUNT_DOWN = 20
BATTLE.ENERGY_HOUSE_ATTACKED = 10
BATTLE.ENERGY_HOUSE_ATTACKED_BOSS = 50
BATTLE.ENERGY_MONSTER_DIED = 1

BATTLE.CARD_STATUS_NORMAL = 0
BATTLE.CARD_STATUS_CLICK = 1
BATTLE.CARD_STATUS_DRAG = 2
BATTLE.NUMBER_OF_NODE_CARD = 4
BATTLE.ENERGY_DESTROY_CARD = 5

BATTLE.ANIMATION_NAME_OF_AS = "animation"
BATTLE.ANIMATION_NAME_OF_ARENA_FOREST = "idle"

BATTLE.RATIO_CONTROL_PANEL_HEIGHT_BY_HEIGHT = 0.17
BATTLE.RATIO_SQUARE_SIZE_BY_HEIGHT = 0.83/14
BATTLE.RATIO_RIVER_HEIGHT_BY_HEIGHT = 0.1259
BATTLE.RATIO_POSITION_TIMER_BACKGROUND_BY_HEIGHT = 0.555

BATTLE.MIN_FIX_CHANGE_FRAME= 0.1
BATTLE.FRAME_PER_SECOND = 30
BATTLE.DELAY_FRAME_TO_CREATE_MONSTER = 10
BATTLE.RATIO_DISTANCE_TO_TURN = 1/4

BATTLE.MONSTER_FLY = 0;
BATTLE.MONSTER_WALK = 1;
BATTLE.STANDARD_SPEED = 50;
BATTLE.STANDARD_WEIGHT = 100;

BATTLE.GAME_GUI_HEIGHT = BATTLE.SQUARE_SIZE * BATTLE.ROWS;

BATTLE.NORMAL_SHADOW = 0;
BATTLE.RED_SHADOW = 1;
BATTLE.BLUE_SHADOW = 2;
BATTLE.NONE_SHADOW = 3;

// =============== SPELL ===============
BATTLE.DELAY_FRAME_FALL_ANIMATION = 6