

var gv = gv || {};

gv.ERROR = {};

gv.ERROR.SUCCESS = 0;
gv.ERROR.CARD_SUCCESS = 0;
gv.ERROR.CARD_USED = 1;
gv.ERROR.CARD_NOT_OWNED = 2;
gv.ERROR.CARD_INDEX_INVALID = 3;
gv.ERROR.CARD_NOT_EXIST = 4;
gv.ERROR.CARD_MAX_LEVEL = 5;
gv.ERROR.CARD_NOT_ENOUGH_PIECE = 6;
gv.ERROR.CHEST_SUCCESS = 0;
gv.ERROR.CHEST_SLOT_IS_FULL = 20;
gv.ERROR.CHEST_OPENING = 21;
gv.ERROR.CHEST_NOT_EXIST = 22;
gv.ERROR.CHEST_NOT_OPENING = 23;
gv.ERROR.INVENTORY_SUCCESS = 0;
gv.ERROR.INVENTORY_GOLD_NOT_ENOUGH = 40;
gv.ERROR.INVENTORY_GEM_NOT_ENOUGH = 41;
gv.ERROR.SHOP_SUCCESS = 0;
gv.ERROR.SHOP_EXPIRED = 60;
gv.ERROR.SHOP_COIN_INDEX_INVALID = 61;
gv.ERROR.SHOP_ITEM_INDEX_INVALID = 62;
gv.ERROR.SHOP_ITEM_WAS_BOUGHT = 63;
gv.ERROR.SHOP_ITEM_INVALID_TYPE = 64;

// Battle
gv.ERROR.SUMMON_EXIST_MONSTER_ON_MAP = 1;

gv.ERROR.MONSTER_NOT_ENOUGH_ENERGY = 20;
gv.ERROR.MONSTER_INVALID_POSITION = 21;
gv.ERROR.MONSTER_INVALID_CARD_USING = 22;

gv.ERROR.SPELL_NOT_ENOUGH_ENERGY = 40;
gv.ERROR.SPELL_INVALID_POSITION = 41;
gv.ERROR.SPELL_INVALID_CARD_USING = 42;
gv.ERROR.SPELL_INVALID_POSITION_MAP = 43;

gv.ERROR.DROP_TOWER_NOT_ENOUGH_ENERGY = 60;
gv.ERROR.DROP_TOWER_INVALID_POSITION = 61;
gv.ERROR.DROP_TOWER_INVALID_CARD_USING = 62;
gv.ERROR.DROP_TOWER_EXIST_OBSTACLE_ON_CELL = 63;
gv.ERROR.DROP_TOWER_EXIST_MONSTER_ON_CELL = 64;
gv.ERROR.DROP_TOWER_BLOCK_WAY_OF_MONSTER = 65;
gv.ERROR.DROP_TOWER_CAN_NOT_MOVE_TO_TARGET = 66;
gv.ERROR.DROP_TOWER_UPGRADE_MAX = 67;
gv.ERROR.DROP_TOWER_UPGRADE_INVALID_CARD = 68;
gv.ERROR.DROP_TOWER_UPGRADE_BUSY = 69;

gv.ERROR.TARGET_OBSTACLE_INVALID_POSITION = 90;

gv.ERROR.CANCEL_TOWER_INVALID_POSITION = 100;

gv.ERROR.CHANGE_TARGET_TOWER_INVALID_POSITION = 120;
gv.ERROR.CHANGE_TARGET_TOWER_INVALID_TARGET_MODE = 121;
gv.ERROR.CHANGE_TARGET_TOWER_INVALID_TOWER_TYPE = 122;

gv.ERROR.CANCEL_CARD_NOT_ENOUGH_ENERGY = 140;
gv.ERROR.CANCEL_CARD_INVALID_INDEX_CARD = 141;